# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "CycleLove Design Co."
email: "hello@cyclelovedesign.co"
description: "Making your cycling brand even better. CycleLove Design Co harnesses storytelling and design to make brands impactful online."
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://cyclelovedesign.co" # the base hostname & protocol for your site
twitter_username: cyclelovedesignco
github_username:  j-greig
googleID: "UA-41226144-3"

# Build settings
permalink: :title
markdown: kramdown
theme: minima
#theme: cyclelovedesignco
gems:
  - jekyll-feed
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock
  - gulpfile.js


# Notes
#
# Commands
# cd /Users/james/Git/cyclelovedesignco
# To start Jeykll: bundle exec jekyll serve
# To start Browsersync: gulp
# Live reloading with Gulp and Browersync: https://nvbn.github.io/2015/06/19/jekyll-browsersync/
